settings.localization =
	name: "название"
	created_at: "дата заказа"
	comment: "комментарий"
	number: "номер"
	deliver_date: "дата доставки"
	credit_procent: "проценты кредита"
	credit_month: "Кол-во месяцев кредита"
	credit_sum: "сумма кредита"
	payment_type: "способ оплаты"
	finalpayment_sum: "сумма окончательного расчета"
	finalpayment_date: "дата окончательного расчета"
	doppayment_sum: "сумма доплаты"
	doppayment_date: "дата доплаты"
	prepayment_sum: "сумма предоплаты"
	prepayment_date: "дата предоплаты"
	deliver_cost: "стоимость доставки"
	deliver_type: "способ доставки"
	manager_tel: "телефон менеджера"
	manager: "менеджер"
	salon_tel: "телефон салона"
	salon: "салон"
	addr_elevator: "лифт"
	addr_code: "код"
	addr_floor: "этаж"
	addr_staircase: "корпус"
	addr_metro: "метро"
	addr_flat: "квартира"
	addr_block: "подъезд"
	addr_home: "дом"
	addr_street: "улица"
	pay_type: "способ оплаты"
	phone: "телефон"
	gender: "пол"
	last_name: "фамилия"
	middle_name: "отчество"
	first_name: "имя"
	status: "Статус"
	product: "Товар"
	orderitem: "Товары в заказе"
	order: "Заказы"